services:
  - type: web
    name: backendAPI
    plan: free
    runtime: node
    repo: https://github.com/jLiucoder/typescript-starter
    buildCommand: npm install; npm run build
    startCommand: npm run start
    
databases:
  - name: mydb
    user: backendAPI
    plan: free